name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Build project
      run: ./build.sh
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.5.0
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: website/ # The folder the action should deploy.
        clean: true # Automatically remove deleted files from the deploy branch
        single-commit: true
